export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_USER_PASS = "SET_USER_PASS";
export const SET_USER_URL = "SET_USER_URL";
export const SET_HOST = "SET_HOST";
export const SET_REGISTER_EXPIRIES = "SET_REGISTER_EXPIRIES";
export const SET_SESSION_TIMERS_REFRESH_METHOD =
	"SET_SESSION_TIMERS_REFRESH_METHOD";
export const SET_RELAMS = "SET_RELAMS";

export const SET_IS_LOADED = "SET_IS_LOADED";
